---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: registry.redhat.io/rhel8/postgresql-12
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - name: tcp
              containerPort: 5432
          env:
            - name: POSTGRESQL_PASSWORD
              value: tradedb
            - name: POSTGRESQL_USER
              value: tradedb
            - name: POSTGRESQL_DATABASE
              value: tradedb
            - name: PG_NETWORK_MASK
              value: all
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: "100"
            - name: POSTGRESQL_SHARED_BUFFERS
              value: "250"
            - name: PG_WORK_MEM
              value: "128"
            - name: POSTGRESQL_EFFECTIVE_CACHE_SIZE
              value: "750"
            - name: PG_EFFECTIVE_IO
              value: "128"
            - name: PG_MAX_WAL_SIZE
              value: "4"
          volumeMounts:
            - mountPath: /pgdata
              name: pgdata
            - mountPath: /pgwal
              name: pgwal
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata-pvc
        - name: pgwal
          persistentVolumeClaim:
            claimName: pgwal-pvc
